2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Configure stats pid to 10624
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Loading settings from C:\Users\admin.DESKTOP-7USASVH\.config\wandb\settings
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Loading settings from D:\Git\IDCDF-WKY\wandb\settings
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'run.py', 'program_abspath': 'd:\\Git\\IDCDF-WKY\\run.py', 'program': 'd:\\Git\\IDCDF-WKY\\run.py'}
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_setup.py:_flush():79] Applying login settings: {}
2025-03-17 21:56:56,059 INFO    MainThread:10624 [wandb_init.py:_log_setup():533] Logging user logs to D:\Git\IDCDF-WKY\wandb\run-20250317_215656-fvwzqikt\logs\debug.log
2025-03-17 21:56:56,074 INFO    MainThread:10624 [wandb_init.py:_log_setup():534] Logging internal logs to D:\Git\IDCDF-WKY\wandb\run-20250317_215656-fvwzqikt\logs\debug-internal.log
2025-03-17 21:56:56,074 INFO    MainThread:10624 [wandb_init.py:init():619] calling init triggers
2025-03-17 21:56:56,074 INFO    MainThread:10624 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'method': 'idcdm', 'epoch': 10, 'seed': 0, 'data_type': 'idcd', 'dtype': torch.float64, 'device': 'cpu', 'batch_size': 256, 'lr': 0.0007, 'test_size': 0.2, 'stu_latent_dim': 64, 'exer_latent_dim': 2, 'name': 'idcdm--seed0'}
2025-03-17 21:56:56,075 INFO    MainThread:10624 [wandb_init.py:init():669] starting backend
2025-03-17 21:56:56,075 INFO    MainThread:10624 [wandb_init.py:init():673] sending inform_init request
2025-03-17 21:56:56,076 INFO    MainThread:10624 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-03-17 21:56:56,079 INFO    MainThread:10624 [wandb_init.py:init():686] backend started and connected
2025-03-17 21:56:56,084 INFO    MainThread:10624 [wandb_init.py:init():781] updated telemetry
2025-03-17 21:56:56,084 INFO    MainThread:10624 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2025-03-17 21:56:56,118 INFO    Thread-5 (wrapped_target):10624 [retry.py:__call__():172] Retry attempt failed:
urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin.DESKTOP-7USASVH\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
2025-03-17 21:56:56,887 INFO    MainThread:10624 [wandb_init.py:init():867] starting run threads in backend
2025-03-17 21:56:57,293 INFO    MainThread:10624 [wandb_run.py:_console_start():2456] atexit reg
2025-03-17 21:56:57,293 INFO    MainThread:10624 [wandb_run.py:_redirect():2305] redirect: wrap_raw
2025-03-17 21:56:57,294 INFO    MainThread:10624 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-03-17 21:56:57,295 INFO    MainThread:10624 [wandb_run.py:_redirect():2395] Redirects installed.
2025-03-17 21:56:57,303 INFO    MainThread:10624 [wandb_init.py:init():911] run started, returning control to user process
2025-03-17 21:56:57,467 WARNING MsgRouterThr:10624 [router.py:message_loop():75] message_loop has been closed
