Number of train_response logs 20025
[Epoch 1]
Training: 100%|█████████████████████████████████████████████████████| 79/79 [00:03<00:00, 23.80it/s]
Average loss: 0.9706287421757662
Evaluating: 100%|███████████████████████████████████████████████████| 21/21 [00:00<00:00, 48.16it/s]
Traceback (most recent call last):
  File "d:\Git\IDCDF-WKY\run.py", line 64, in <module>
    sys.exit(main(config_dict))
             ^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\run.py", line 62, in main
    idcdm.train(datahub, "train", "test", valid_metrics=metrics, batch_size=config['batch_size'],epoch=config['epoch'], lr=config['lr'])
  File "d:\Git\IDCDF-WKY\inscd\models\idcdm.py", line 45, in train
    self._train(datahub=datahub, set_type=set_type,
  File "d:\Git\IDCDF-WKY\inscd\_base.py", line 52, in _train
    self.score(datahub, valid_set_type, valid_metrics, **kwargs)
  File "d:\Git\IDCDF-WKY\inscd\models\idcdm.py", line 57, in score
    return self._score(datahub=datahub, set_type=set_type, metrics=metrics, batch_size=batch_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\inscd\_listener.py", line 33, in wrapper
    result = self.__format(func(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\inscd\_base.py", line 67, in _score
    return ruler(self, datahub, set_type, pred_r, metrics)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\inscd\_ruler.py", line 160, in __call__
    results[metric] = self.__method_map[metric](mastery_level, datahub, set_type)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\inscd\_ruler.py", line 113, in degree_of_agreement
    concepts = datahub.top_k_concepts(self.top_k_doa)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Git\IDCDF-WKY\inscd\datahub.py", line 45, in top_k_concepts
    raise ValueError("Dataset \"{}\" does not exist. If you create your new dataset via \"load_data()\", "
ValueError: Dataset "total" does not exist. If you create your new dataset via "load_data()", the parameter "dataset" is one of the dict_keys(['train', 'test', 'all'])
